# generated from tests.py by /home/cs1521/public_html/19T3/scripts//autotest_update_from_solution

max_cpu=30
command=1521 spim -f count.s
files=count.s


0 stdin="6\n" expected_stdout="Loaded: /home/cs1521/share/spim/exceptions.s\nEnter a number: 1\n2\n3\n4\n5\n6\n"
1 stdin="10\n" expected_stdout="Loaded: /home/cs1521/share/spim/exceptions.s\nEnter a number: 1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n"
2 stdin="11\n" expected_stdout="Loaded: /home/cs1521/share/spim/exceptions.s\nEnter a number: 1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n"
3 stdin="12\n" expected_stdout="Loaded: /home/cs1521/share/spim/exceptions.s\nEnter a number: 1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n"
4 stdin="42\n" expected_stdout="Loaded: /home/cs1521/share/spim/exceptions.s\nEnter a number: 1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n"
5 stdin="75\n" expected_stdout="Loaded: /home/cs1521/share/spim/exceptions.s\nEnter a number: 1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60\n61\n62\n63\n64\n65\n66\n67\n68\n69\n70\n71\n72\n73\n74\n75\n"
